db = db.getSiblingDB("db_standard_code");

db.createUser({
  user: "stdUser",
  pwd: "Sup3I2Adm1n",
  roles: [
    {
      role: "readWrite",
      db: "db_standard_code",
    },
  ],
});

db.createCollection("countries");

db.countries.insertMany([
  {
    countryCode: "ABW",
    countryNameTH: "อารูบา",
    countryNameEN: "Aruba",
    ISO: "AW",
  },
  {
    countryCode: "AFG",
    countryNameTH: "อัฟกานิสถาน",
    countryNameEN: "Afghanistan",
    ISO: "AF",
  },
  {
    countryCode: "AGO",
    countryNameTH: "แองโกลา",
    countryNameEN: "Angola",
    ISO: "AO",
  },
  {
    countryCode: "AIA",
    countryNameTH: "แองกวิลลา",
    countryNameEN: "Anguilla",
    ISO: "AI",
  },
  {
    countryCode: "ALA",
    countryNameTH: "โอลันด์",
    countryNameEN: "Åland",
    ISO: "AX",
  },
  {
    countryCode: "ALB",
    countryNameTH: "แอลเบเนีย",
    countryNameEN: "Albania",
    ISO: "AL",
  },
  {
    countryCode: "AND",
    countryNameTH: "อันดอร์รา",
    countryNameEN: "Andorra",
    ISO: "AD",
  },
  {
    countryCode: "ARE",
    countryNameTH: "สหรัฐอาหรับเอมิเรตส์\n",
    countryNameEN: "United Arab Emirates",
    ISO: "AE",
  },
  {
    countryCode: "ARG",
    countryNameTH: "อาร์เจนตินา",
    countryNameEN: "Argentina",
    ISO: "AR",
  },
  {
    countryCode: "ARM",
    countryNameTH: "อาร์เมเนีย",
    countryNameEN: "Armenia",
    ISO: "AM",
  },
  {
    countryCode: "ASM",
    countryNameTH: "อเมริกันซามัว",
    countryNameEN: "American Samoa",
    ISO: "AS",
  },
  {
    countryCode: "ATA",
    countryNameTH: "ทวิปแอนตาร์กติกา",
    countryNameEN: "Antarctica",
    ISO: "AQ",
  },
  {
    countryCode: "ATF",
    countryNameTH: "ดินแดนทางตอนใต้ของฝรั่งเศส",
    countryNameEN: "French Southern Territories",
    ISO: "TF",
  },
  {
    countryCode: "ATG",
    countryNameTH: "แอนติกาและบาร์บูดา",
    countryNameEN: "Antigua and Barbuda",
    ISO: "AG",
  },
  {
    countryCode: "AUS",
    countryNameTH: "ออสเตรเลีย",
    countryNameEN: "Australia",
    ISO: "AU",
  },
  {
    countryCode: "AUT",
    countryNameTH: "ออสเตรีย",
    countryNameEN: "Austria",
    ISO: "AT",
  },
  {
    countryCode: "AZE",
    countryNameTH: "อาเซอร์ไบจาน",
    countryNameEN: "Azerbaijan",
    ISO: "AZ",
  },
  {
    countryCode: "BDI",
    countryNameTH: "บุรุนดี",
    countryNameEN: "Burundi",
    ISO: "BI",
  },
  {
    countryCode: "BEL",
    countryNameTH: "เบลเยียม",
    countryNameEN: "Belgium",
    ISO: "BE",
  },
  {
    countryCode: "BEN",
    countryNameTH: "เบนิน",
    countryNameEN: "Benin",
    ISO: "BJ",
  },
  {
    countryCode: "BES",
    countryNameTH: "โบแนร์",
    countryNameEN: "Bonaire",
    ISO: "BQ",
  },
  {
    countryCode: "BFA",
    countryNameTH: "บูร์กินาฟาโซ",
    countryNameEN: "Burkina Faso",
    ISO: "BF",
  },
  {
    countryCode: "BGD",
    countryNameTH: "บังคลาเทศ",
    countryNameEN: "Bangladesh",
    ISO: "BD",
  },
  {
    countryCode: "BGR",
    countryNameTH: "บัลแกเรีย",
    countryNameEN: "Bulgaria",
    ISO: "BG",
  },
  {
    countryCode: "BHR",
    countryNameTH: "บาห์เรน",
    countryNameEN: "Bahrain",
    ISO: "BH",
  },
  {
    countryCode: "BHS",
    countryNameTH: "บาฮามาส",
    countryNameEN: "Bahamas",
    ISO: "BS",
  },
  {
    countryCode: "BIH",
    countryNameTH: "บอสเนียและเฮอร์เซโก\n",
    countryNameEN: "Bosnia and Herzegovina",
    ISO: "BA",
  },
  {
    countryCode: "BLM",
    countryNameTH: "Saint Barthélemy",
    countryNameEN: "Saint Barthélemy",
    ISO: "BL",
  },
  {
    countryCode: "BLR",
    countryNameTH: "เบลารุส",
    countryNameEN: "Belarus",
    ISO: "BY",
  },
  {
    countryCode: "BLZ",
    countryNameTH: "เบลีซ",
    countryNameEN: "Belize",
    ISO: "BZ",
  },
  {
    countryCode: "BMU",
    countryNameTH: "เบอร์มิวดา",
    countryNameEN: "Bermuda",
    ISO: "BM",
  },
  {
    countryCode: "BOL",
    countryNameTH: "โบลิเวีย",
    countryNameEN: "Bolivia",
    ISO: "BO",
  },
  {
    countryCode: "BRA",
    countryNameTH: "บราซิล",
    countryNameEN: "Brazil",
    ISO: "BR",
  },
  {
    countryCode: "BRB",
    countryNameTH: "บาร์เบโดส",
    countryNameEN: "Barbados",
    ISO: "BB",
  },
  {
    countryCode: "BRN",
    countryNameTH: "บรูไน",
    countryNameEN: "Brunei",
    ISO: "BN",
  },
  {
    countryCode: "BTN",
    countryNameTH: "ภูฏาน",
    countryNameEN: "Bhutan",
    ISO: "BT",
  },
  {
    countryCode: "BVT",
    countryNameTH: "เกาะบูเว็ต",
    countryNameEN: "Bouvet Island",
    ISO: "BV",
  },
  {
    countryCode: "BWA",
    countryNameTH: "บอตสวานา",
    countryNameEN: "Botswana",
    ISO: "BW",
  },
  {
    countryCode: "CAF",
    countryNameTH: "สาธารณรัฐแอฟริกากลาง",
    countryNameEN: "Central African Republic",
    ISO: "CF",
  },
  {
    countryCode: "CAN",
    countryNameTH: "แคนาดา",
    countryNameEN: "Canada",
    ISO: "CA",
  },
  {
    countryCode: "CCK",
    countryNameTH: "เกาะโคโคส [คีลิง]",
    countryNameEN: "Cocos [Keeling] Islands",
    ISO: "CC",
  },
  {
    countryCode: "CHE",
    countryNameTH: "สวิสเซอร์แลนด์",
    countryNameEN: "Switzerland",
    ISO: "CH",
  },
  {
    countryCode: "CHL",
    countryNameTH: "ชิลี",
    countryNameEN: "Chile",
    ISO: "CL",
  },
  {
    countryCode: "CHN",
    countryNameTH: "จีน",
    countryNameEN: "China",
    ISO: "CN",
  },
  {
    countryCode: "CIV",
    countryNameTH: "ไอวอรี่โคสต์",
    countryNameEN: "Ivory Coast",
    ISO: "CI",
  },
  {
    countryCode: "CMR",
    countryNameTH: "แคเมอรูน",
    countryNameEN: "Cameroon",
    ISO: "CM",
  },
  {
    countryCode: "COD",
    countryNameTH: "สาธารณรัฐประชาธิปไตยคองโก",
    countryNameEN: "Democratic Republic of the Congo",
    ISO: "CD",
  },
  {
    countryCode: "COG",
    countryNameTH: "สาธารณรัฐคองโก",
    countryNameEN: "Republic of the Congo",
    ISO: "CG",
  },
  {
    countryCode: "COK",
    countryNameTH: "หมู่เกาะคุก",
    countryNameEN: "Cook Islands",
    ISO: "CK",
  },
  {
    countryCode: "COL",
    countryNameTH: "โคลอมเบีย",
    countryNameEN: "Colombia",
    ISO: "CO",
  },
  {
    countryCode: "COM",
    countryNameTH: "คอโมโรส",
    countryNameEN: "Comoros",
    ISO: "KM",
  },
  {
    countryCode: "CPV",
    countryNameTH: "เคปเวิร์ด",
    countryNameEN: "Cape Verde",
    ISO: "CV",
  },
  {
    countryCode: "CRI",
    countryNameTH: "คอสตาริกา\n",
    countryNameEN: "Costa Rica",
    ISO: "CR",
  },
  {
    countryCode: "CUB",
    countryNameTH: "คิวบา",
    countryNameEN: "Cuba",
    ISO: "CU",
  },
  {
    countryCode: "CUW",
    countryNameTH: "คูราเซา\n",
    countryNameEN: "Curacao",
    ISO: "CW",
  },
  {
    countryCode: "CXR",
    countryNameTH: "เกาะคริสต์มาส",
    countryNameEN: "Christmas Island",
    ISO: "CX",
  },
  {
    countryCode: "CYM",
    countryNameTH: "หมู่เกาะเคย์เเมน",
    countryNameEN: "Cayman Islands",
    ISO: "KY",
  },
  {
    countryCode: "CYP",
    countryNameTH: "ไซปรัส",
    countryNameEN: "Cyprus",
    ISO: "CY",
  },
  {
    countryCode: "CZE",
    countryNameTH: "สาธารณรัฐเช็ก",
    countryNameEN: "Czech Republic",
    ISO: "CZ",
  },
  {
    countryCode: "DEU",
    countryNameTH: "เยอรมันนี",
    countryNameEN: "Germany",
    ISO: "DE",
  },
  {
    countryCode: "DJI",
    countryNameTH: "จิบูตี",
    countryNameEN: "Djibouti",
    ISO: "DJ",
  },
  {
    countryCode: "DMA",
    countryNameTH: "โดมินิกา",
    countryNameEN: "Dominica",
    ISO: "DM",
  },
  {
    countryCode: "DNK",
    countryNameTH: "เดนมาร์ก",
    countryNameEN: "Denmark",
    ISO: "DK",
  },
  {
    countryCode: "DOM",
    countryNameTH: "สาธารณรัฐโดมินิกัน\n",
    countryNameEN: "Dominican Republic",
    ISO: "DO",
  },
  {
    countryCode: "DZA",
    countryNameTH: "แอลจีเรีย",
    countryNameEN: "Algeria",
    ISO: "DZ",
  },
  {
    countryCode: "ECU",
    countryNameTH: "เอกวาดอร์",
    countryNameEN: "Ecuador",
    ISO: "EC",
  },
  {
    countryCode: "EGY",
    countryNameTH: "อียิปต์",
    countryNameEN: "Egypt",
    ISO: "EG",
  },
  {
    countryCode: "ERI",
    countryNameTH: "เอริเทรี",
    countryNameEN: "Eritrea",
    ISO: "ER",
  },
  {
    countryCode: "ESH",
    countryNameTH: "ซาฮาร่าตะวันตก",
    countryNameEN: "Western Sahara",
    ISO: "EH",
  },
  {
    countryCode: "ESP",
    countryNameTH: "สเปน",
    countryNameEN: "Spain",
    ISO: "ES",
  },
  {
    countryCode: "EST",
    countryNameTH: "เอสโตเนีย",
    countryNameEN: "Estonia",
    ISO: "EE",
  },
  {
    countryCode: "ETH",
    countryNameTH: "สาธารณรัฐเอธิโอเปีย",
    countryNameEN: "Ethiopia",
    ISO: "ET",
  },
  {
    countryCode: "FIN",
    countryNameTH: "ฟินแลนด์",
    countryNameEN: "Finland",
    ISO: "FI",
  },
  {
    countryCode: "FJI",
    countryNameTH: "ฟิจิ",
    countryNameEN: "Fiji",
    ISO: "FJ",
  },
  {
    countryCode: "FLK",
    countryNameTH: "หมู่เกาะฟอล์คแลนด์",
    countryNameEN: "Falkland Islands",
    ISO: "FK",
  },
  {
    countryCode: "FRA",
    countryNameTH: "ฝรั่งเศส",
    countryNameEN: "France",
    ISO: "FR",
  },
  {
    countryCode: "FRO",
    countryNameTH: "หมู่เกาะแฟโร",
    countryNameEN: "Faroe Islands",
    ISO: "FO",
  },
  {
    countryCode: "FSM",
    countryNameTH: "ไมโครนีเซีย",
    countryNameEN: "Micronesia",
    ISO: "FM",
  },
  {
    countryCode: "GAB",
    countryNameTH: "กาบอง",
    countryNameEN: "Gabon",
    ISO: "GA",
  },
  {
    countryCode: "GBR",
    countryNameTH: "อังกฤษ (สหราชอาณาจักร)",
    countryNameEN: "United Kingdom",
    ISO: "GB",
  },
  {
    countryCode: "GEO",
    countryNameTH: "จอร์เจีย",
    countryNameEN: "Georgia",
    ISO: "GE",
  },
  {
    countryCode: "GGY",
    countryNameTH: "เกิร์นซีย์",
    countryNameEN: "Guernsey",
    ISO: "GG",
  },
  {
    countryCode: "GHA",
    countryNameTH: "เกิร์นซีย์",
    countryNameEN: "Ghana",
    ISO: "GH",
  },
  {
    countryCode: "GIB",
    countryNameTH: "ยิบรอลตา",
    countryNameEN: "Gibraltar",
    ISO: "GI",
  },
  {
    countryCode: "GIN",
    countryNameTH: "กินี",
    countryNameEN: "Guinea",
    ISO: "GN",
  },
  {
    countryCode: "GLP",
    countryNameTH: "กัวเดลุฟ",
    countryNameEN: "Guadeloupe",
    ISO: "GP",
  },
  {
    countryCode: "GMB",
    countryNameTH: "แกมเบีย",
    countryNameEN: "Gambia",
    ISO: "GM",
  },
  {
    countryCode: "GNB",
    countryNameTH: "กินีบิสเซา",
    countryNameEN: "Guinea-Bissau",
    ISO: "GW",
  },
  {
    countryCode: "GNQ",
    countryNameTH: "อิเควทอเรียลกินี",
    countryNameEN: "Equatorial Guinea",
    ISO: "GQ",
  },
  {
    countryCode: "GRC",
    countryNameTH: "กรีซ",
    countryNameEN: "Greece",
    ISO: "GR",
  },
  {
    countryCode: "GRD",
    countryNameTH: "เกรเนดา ",
    countryNameEN: "Grenada",
    ISO: "GD",
  },
  {
    countryCode: "GRL",
    countryNameTH: "กรีนแลนด์",
    countryNameEN: "Greenland",
    ISO: "GL",
  },
  {
    countryCode: "GTM",
    countryNameTH: "กัวเตมาลา",
    countryNameEN: "Guatemala",
    ISO: "GT",
  },
  {
    countryCode: "GUF",
    countryNameTH: "เฟรนช์เกียนา",
    countryNameEN: "French Guiana",
    ISO: "GF",
  },
  {
    countryCode: "GUM",
    countryNameTH: "เกาะกวม",
    countryNameEN: "Guam",
    ISO: "GU",
  },
  {
    countryCode: "GUY",
    countryNameTH: "กายอานา",
    countryNameEN: "Guyana",
    ISO: "GY",
  },
  {
    countryCode: "HKG",
    countryNameTH: "ฮ่องกง",
    countryNameEN: "Hong Kong",
    ISO: "HK",
  },
  {
    countryCode: "HMD",
    countryNameTH: "เกาะเฮิร์ดและหมู่เกาะแมคโดนัลด์",
    countryNameEN: "Heard Island and McDonald Islands",
    ISO: "HM",
  },
  {
    countryCode: "HND",
    countryNameTH: "ฮอนดูรัส",
    countryNameEN: "Honduras",
    ISO: "HN",
  },
  {
    countryCode: "HRV",
    countryNameTH: "โครเอเชีย",
    countryNameEN: "Croatia",
    ISO: "HR",
  },
  {
    countryCode: "HTI",
    countryNameTH: "เฮติ",
    countryNameEN: "Haiti",
    ISO: "HT",
  },
  {
    countryCode: "HUN",
    countryNameTH: "ฮังการี",
    countryNameEN: "Hungary",
    ISO: "HU",
  },
  {
    countryCode: "IDN",
    countryNameTH: "อินโดนีเซีย",
    countryNameEN: "Indonesia",
    ISO: "ID",
  },
  {
    countryCode: "IMN",
    countryNameTH: "เกาะแมน",
    countryNameEN: "Isle of Man",
    ISO: "IM",
  },
  {
    countryCode: "IND",
    countryNameTH: "อินเดีย",
    countryNameEN: "India",
    ISO: "IN",
  },
  {
    countryCode: "IOT",
    countryNameTH: "หมู่เกาะบริติชเวอร์จิน",
    countryNameEN: "British Indian Ocean Territory",
    ISO: "IO",
  },
  {
    countryCode: "IRL",
    countryNameTH: "ไอร์แลนด์",
    countryNameEN: "Ireland",
    ISO: "IE",
  },
  {
    countryCode: "IRN",
    countryNameTH: "อิหร่าน",
    countryNameEN: "Iran",
    ISO: "IR",
  },
  {
    countryCode: "IRQ",
    countryNameTH: "อิรัก",
    countryNameEN: "Iraq",
    ISO: "IQ",
  },
  {
    countryCode: "ISL",
    countryNameTH: "ประเทศไอซ์แลนด์",
    countryNameEN: "Iceland",
    ISO: "IS",
  },
  {
    countryCode: "ISR",
    countryNameTH: "อิสราเอล",
    countryNameEN: "Israel",
    ISO: "IL",
  },
  {
    countryCode: "ITA",
    countryNameTH: "อิตาลี",
    countryNameEN: "Italy",
    ISO: "IT",
  },
  {
    countryCode: "JAM",
    countryNameTH: "เกาะจาเมกา",
    countryNameEN: "Jamaica",
    ISO: "JM",
  },
  {
    countryCode: "JEY",
    countryNameTH: "นิวเจอร์ซีย์",
    countryNameEN: "Jersey",
    ISO: "JE",
  },
  {
    countryCode: "JOR",
    countryNameTH: "จอร์แดน",
    countryNameEN: "Jordan",
    ISO: "JO",
  },
  {
    countryCode: "JPN",
    countryNameTH: "ญี่ปุ่น",
    countryNameEN: "Japan",
    ISO: "JP",
  },
  {
    countryCode: "KAZ",
    countryNameTH: "คาซัคสถาน",
    countryNameEN: "Kazakhstan",
    ISO: "KZ",
  },
  {
    countryCode: "KEN",
    countryNameTH: "เคนย่า",
    countryNameEN: "Kenya",
    ISO: "KE",
  },
  {
    countryCode: "KGZ",
    countryNameTH: "คีร์กีสถาน",
    countryNameEN: "Kyrgyzstan",
    ISO: "KG",
  },
  {
    countryCode: "KHM",
    countryNameTH: "กัมพูชา",
    countryNameEN: "Cambodia",
    ISO: "KH",
  },
  {
    countryCode: "KIR",
    countryNameTH: "คิริบาส",
    countryNameEN: "Kiribati",
    ISO: "KI",
  },
  {
    countryCode: "KNA",
    countryNameTH: "เซนต์คิตส์และเนวิส",
    countryNameEN: "Saint Kitts and Nevis",
    ISO: "KN",
  },
  {
    countryCode: "KOR",
    countryNameTH: "เกาหลีใต้",
    countryNameEN: "South Korea",
    ISO: "KR",
  },
  {
    countryCode: "KWT",
    countryNameTH: "คูเวต",
    countryNameEN: "Kuwait",
    ISO: "KW",
  },
  {
    countryCode: "LAO",
    countryNameTH: "ลาว",
    countryNameEN: "Laos",
    ISO: "LA",
  },
  {
    countryCode: "LBN",
    countryNameTH: "เลบานอน",
    countryNameEN: "Lebanon",
    ISO: "LB",
  },
  {
    countryCode: "LBR",
    countryNameTH: "ประเทศไลบีเรีย",
    countryNameEN: "Liberia",
    ISO: "LR",
  },
  {
    countryCode: "LBY",
    countryNameTH: "ลิบยา",
    countryNameEN: "Libya",
    ISO: "LY",
  },
  {
    countryCode: "LCA",
    countryNameTH: "เซนต์ลูเซีย",
    countryNameEN: "Saint Lucia",
    ISO: "LC",
  },
  {
    countryCode: "LIE",
    countryNameTH: "นสไตน์",
    countryNameEN: "Liechtenstein",
    ISO: "LI",
  },
  {
    countryCode: "LKA",
    countryNameTH: "ศรีลังกา",
    countryNameEN: "Sri Lanka",
    ISO: "LK",
  },
  {
    countryCode: "LSO",
    countryNameTH: "เลโซโท",
    countryNameEN: "Lesotho",
    ISO: "LS",
  },
  {
    countryCode: "LTU",
    countryNameTH: "ลิธัวเนีย",
    countryNameEN: "Lithuania",
    ISO: "LT",
  },
  {
    countryCode: "LUX",
    countryNameTH: "ลักเซมเบิร์ก",
    countryNameEN: "Luxembourg",
    ISO: "LU",
  },
  {
    countryCode: "LVA",
    countryNameTH: "ลัตเวีย",
    countryNameEN: "Latvia",
    ISO: "LV",
  },
  {
    countryCode: "MAC",
    countryNameTH: "มาเก๊า",
    countryNameEN: "Macao",
    ISO: "MO",
  },
  {
    countryCode: "MAF",
    countryNameTH: "เซนต์มาร์ติน",
    countryNameEN: "Saint Martin",
    ISO: "MF",
  },
  {
    countryCode: "MAR",
    countryNameTH: "โมร็อกโก",
    countryNameEN: "Morocco",
    ISO: "MA",
  },
  {
    countryCode: "MCO",
    countryNameTH: "โมนาโก",
    countryNameEN: "Monaco",
    ISO: "MC",
  },
  {
    countryCode: "MDA",
    countryNameTH: "มอลโดวา",
    countryNameEN: "Moldova",
    ISO: "MD",
  },
  {
    countryCode: "MDG",
    countryNameTH: "มาดากัสการ์",
    countryNameEN: "Madagascar",
    ISO: "MG",
  },
  {
    countryCode: "MDV",
    countryNameTH: "มัลดีฟส์",
    countryNameEN: "Maldives",
    ISO: "MV",
  },
  {
    countryCode: "MEX",
    countryNameTH: "เม็กซิโก",
    countryNameEN: "Mexico",
    ISO: "MX",
  },
  {
    countryCode: "MHL",
    countryNameTH: "หมู่เกาะมาร์แชลล์",
    countryNameEN: "Marshall Islands",
    ISO: "MH",
  },
  {
    countryCode: "MKD",
    countryNameTH: "มาซิโดเนีย",
    countryNameEN: "Macedonia",
    ISO: "MK",
  },
  {
    countryCode: "MLI",
    countryNameTH: "มาลี",
    countryNameEN: "Mali",
    ISO: "ML",
  },
  {
    countryCode: "MLT",
    countryNameTH: "เกาะมอลตา",
    countryNameEN: "Malta",
    ISO: "MT",
  },
  {
    countryCode: "MMR",
    countryNameTH: "พม่า",
    countryNameEN: "Myanmar [Burma]",
    ISO: "MM",
  },
  {
    countryCode: "MNE",
    countryNameTH: "มอนเตเนโก",
    countryNameEN: "Montenegro",
    ISO: "ME",
  },
  {
    countryCode: "MNG",
    countryNameTH: "มองโกเลีย",
    countryNameEN: "Mongolia",
    ISO: "MN",
  },
  {
    countryCode: "MNP",
    countryNameTH: "หมู่เกาะนอร์เทิร์นมาเรียนา",
    countryNameEN: "Northern Mariana Islands",
    ISO: "MP",
  },
  {
    countryCode: "MOZ",
    countryNameTH: "โมซัมบิก",
    countryNameEN: "Mozambique",
    ISO: "MZ",
  },
  {
    countryCode: "MRT",
    countryNameTH: "มอริเตเนีย",
    countryNameEN: "Mauritania",
    ISO: "MR",
  },
  {
    countryCode: "MSR",
    countryNameTH: "มอนต์เซอร์รัต",
    countryNameEN: "Montserrat",
    ISO: "MS",
  },
  {
    countryCode: "MTQ",
    countryNameTH: "มาร์ตินีก",
    countryNameEN: "Martinique",
    ISO: "MQ",
  },
  {
    countryCode: "MUS",
    countryNameTH: "มอริเชียส",
    countryNameEN: "Mauritius",
    ISO: "MU",
  },
  {
    countryCode: "MWI",
    countryNameTH: "มาลาวี",
    countryNameEN: "Malawi",
    ISO: "MW",
  },
  {
    countryCode: "MYS",
    countryNameTH: "มาเลเซีย",
    countryNameEN: "Malaysia",
    ISO: "MY",
  },
  {
    countryCode: "MYT",
    countryNameTH: "มายอต",
    countryNameEN: "Mayotte",
    ISO: "YT",
  },
  {
    countryCode: "NAM",
    countryNameTH: "นามิเบีย",
    countryNameEN: "Namibia",
    ISO: "NA",
  },
  {
    countryCode: "NCL",
    countryNameTH: "นิวแคลิโดเนีย",
    countryNameEN: "New Caledonia",
    ISO: "NC",
  },
  {
    countryCode: "NER",
    countryNameTH: "ไนเธอร์",
    countryNameEN: "Niger",
    ISO: "NE",
  },
  {
    countryCode: "NFK",
    countryNameTH: "เกาะนอร์ฟอล์ก",
    countryNameEN: "Norfolk Island",
    ISO: "NF",
  },
  {
    countryCode: "NGA",
    countryNameTH: "ไนจีเรีย",
    countryNameEN: "Nigeria",
    ISO: "NG",
  },
  {
    countryCode: "NIC",
    countryNameTH: "นิการากัว",
    countryNameEN: "Nicaragua",
    ISO: "NI",
  },
  {
    countryCode: "NIU",
    countryNameTH: "นีอูเอ",
    countryNameEN: "Niue",
    ISO: "NU",
  },
  {
    countryCode: "NLD",
    countryNameTH: "เนเธอร์แลนด์",
    countryNameEN: "Netherlands",
    ISO: "NL",
  },
  {
    countryCode: "NOR",
    countryNameTH: "นอร์เวย์",
    countryNameEN: "Norway",
    ISO: "NO",
  },
  {
    countryCode: "NPL",
    countryNameTH: "เนปาล",
    countryNameEN: "Nepal",
    ISO: "NP",
  },
  {
    countryCode: "NRU",
    countryNameTH: "นาอูรู",
    countryNameEN: "Nauru",
    ISO: "NR",
  },
  {
    countryCode: "NZL",
    countryNameTH: "นิวซีแลนด์",
    countryNameEN: "New Zealand",
    ISO: "NZ",
  },
  {
    countryCode: "OMN",
    countryNameTH: "โอมาน",
    countryNameEN: "Oman",
    ISO: "OM",
  },
  {
    countryCode: "PAK",
    countryNameTH: "ปากีสถาน",
    countryNameEN: "Pakistan",
    ISO: "PK",
  },
  {
    countryCode: "PAN",
    countryNameTH: "ปานามา",
    countryNameEN: "Panama",
    ISO: "PA",
  },
  {
    countryCode: "PCN",
    countryNameTH: "หมู่เกาะพิตแคร์น",
    countryNameEN: "Pitcairn Islands",
    ISO: "PN",
  },
  {
    countryCode: "PER",
    countryNameTH: "เปรู",
    countryNameEN: "Peru",
    ISO: "PE",
  },
  {
    countryCode: "PHL",
    countryNameTH: "ฟิลิปปินส์",
    countryNameEN: "Philippines",
    ISO: "PH",
  },
  {
    countryCode: "PLW",
    countryNameTH: "ปาเลา",
    countryNameEN: "Palau",
    ISO: "PW",
  },
  {
    countryCode: "PNG",
    countryNameTH: "ปาปัวนิวกินี",
    countryNameEN: "Papua New Guinea",
    ISO: "PG",
  },
  {
    countryCode: "POL",
    countryNameTH: "โปแลนด์",
    countryNameEN: "Poland",
    ISO: "PL",
  },
  {
    countryCode: "PRI",
    countryNameTH: "เปอร์โตริโก",
    countryNameEN: "Puerto Rico",
    ISO: "PR",
  },
  {
    countryCode: "PRK",
    countryNameTH: "เกาหลีเหนือ",
    countryNameEN: "North Korea",
    ISO: "KP",
  },
  {
    countryCode: "PRT",
    countryNameTH: "โปรตุเกส",
    countryNameEN: "Portugal",
    ISO: "PT",
  },
  {
    countryCode: "PRY",
    countryNameTH: "ปารากวัย",
    countryNameEN: "Paraguay",
    ISO: "PY",
  },
  {
    countryCode: "PSE",
    countryNameTH: "ปาเลสไตน์",
    countryNameEN: "Palestine",
    ISO: "PS",
  },
  {
    countryCode: "PYF",
    countryNameTH: "เฟรนช์โปลินีเซีย",
    countryNameEN: "French Polynesia",
    ISO: "PF",
  },
  {
    countryCode: "QAT",
    countryNameTH: "กาตาร์",
    countryNameEN: "Qatar",
    ISO: "QA",
  },
  {
    countryCode: "REU",
    countryNameTH: "เรอูนียง",
    countryNameEN: "Réunion",
    ISO: "RE",
  },
  {
    countryCode: "ROU",
    countryNameTH: "โรมาเนีย",
    countryNameEN: "Romania",
    ISO: "RO",
  },
  {
    countryCode: "RUS",
    countryNameTH: "รัสเซีย",
    countryNameEN: "Russia",
    ISO: "RU",
  },
  {
    countryCode: "RWA",
    countryNameTH: "รวันดา",
    countryNameEN: "Rwanda",
    ISO: "RW",
  },
  {
    countryCode: "SAU",
    countryNameTH: "ซาอุดิอาราเบีย",
    countryNameEN: "Saudi Arabia",
    ISO: "SA",
  },
  {
    countryCode: "SDN",
    countryNameTH: "ซูดาน",
    countryNameEN: "Sudan",
    ISO: "SD",
  },
  {
    countryCode: "SEN",
    countryNameTH: "เซเนกัล",
    countryNameEN: "Senegal",
    ISO: "SN",
  },
  {
    countryCode: "SGP",
    countryNameTH: "สิงคโปร์",
    countryNameEN: "Singapore",
    ISO: "SG",
  },
  {
    countryCode: "SGS",
    countryNameTH: "หมู่เกาะเซาท์จอร์เจียและหมู่เกาะเซาท์แซนด์วิช",
    countryNameEN: "South Georgia and the South Sandwich Islands",
    ISO: "GS",
  },
  {
    countryCode: "SHN",
    countryNameTH: "เซนต์เฮเลนา",
    countryNameEN: "Saint Helena",
    ISO: "SH",
  },
  {
    countryCode: "SJM",
    countryNameTH: "สฟาลบาร์และยานไมเอน",
    countryNameEN: "Svalbard and Jan Mayen",
    ISO: "SJ",
  },
  {
    countryCode: "SLB",
    countryNameTH: "หมู่เกาะโซโลมอน",
    countryNameEN: "Solomon Islands",
    ISO: "SB",
  },
  {
    countryCode: "SLE",
    countryNameTH: "เซียร์ราลีโอน",
    countryNameEN: "Sierra Leone",
    ISO: "SL",
  },
  {
    countryCode: "SLV",
    countryNameTH: "เอลซัลวาดอร์",
    countryNameEN: "El Salvador",
    ISO: "SV",
  },
  {
    countryCode: "SMR",
    countryNameTH: "ซานมาริโน",
    countryNameEN: "San Marino",
    ISO: "SM",
  },
  {
    countryCode: "SOM",
    countryNameTH: "โซมาเลีย",
    countryNameEN: "Somalia",
    ISO: "SO",
  },
  {
    countryCode: "SPM",
    countryNameTH: "เซนต์ปิแอร์และมีเกอลง",
    countryNameEN: "Saint Pierre and Miquelon",
    ISO: "PM",
  },
  {
    countryCode: "SRB",
    countryNameTH: "เซอร์เบีย",
    countryNameEN: "Serbia",
    ISO: "RS",
  },
  {
    countryCode: "SSD",
    countryNameTH: "ซูดานใต้",
    countryNameEN: "South Sudan",
    ISO: "SS",
  },
  {
    countryCode: "STP",
    countryNameTH: "เซาตูเมและปรินซิปี",
    countryNameEN: "São Tomé and Príncipe",
    ISO: "ST",
  },
  {
    countryCode: "SUR",
    countryNameTH: "ซูรินาเม",
    countryNameEN: "Suriname",
    ISO: "SR",
  },
  {
    countryCode: "SVK",
    countryNameTH: "สโลวะเกีย",
    countryNameEN: "Slovakia",
    ISO: "SK",
  },
  {
    countryCode: "SVN",
    countryNameTH: "สโลวีเนีย",
    countryNameEN: "Slovenia",
    ISO: "SI",
  },
  {
    countryCode: "SWE",
    countryNameTH: "สวีเดน",
    countryNameEN: "Sweden",
    ISO: "SE",
  },
  {
    countryCode: "SWZ",
    countryNameTH: "สวาซิแลนด์",
    countryNameEN: "Swaziland",
    ISO: "SZ",
  },
  {
    countryCode: "SXM",
    countryNameTH: "เกาะเซนต์มาร์ติน",
    countryNameEN: "Sint Maarten",
    ISO: "SX",
  },
  {
    countryCode: "SYC",
    countryNameTH: "เซเชลส์",
    countryNameEN: "Seychelles",
    ISO: "SC",
  },
  {
    countryCode: "SYR",
    countryNameTH: "ซีเรีย",
    countryNameEN: "Syria",
    ISO: "SY",
  },
  {
    countryCode: "TCA",
    countryNameTH: "หมู่เกาะเติกส์และหมู่เกาะเคคอส",
    countryNameEN: "Turks and Caicos Islands",
    ISO: "TC",
  },
  {
    countryCode: "TCD",
    countryNameTH: "ชาด",
    countryNameEN: "Chad",
    ISO: "TD",
  },
  {
    countryCode: "TGO",
    countryNameTH: "โตโก",
    countryNameEN: "Togo",
    ISO: "TG",
  },
  {
    countryCode: "THA",
    countryNameTH: "ไทย",
    countryNameEN: "Thailand",
    ISO: "TH",
  },
  {
    countryCode: "TJK",
    countryNameTH: "ทาจิกิสถาน",
    countryNameEN: "Tajikistan",
    ISO: "TJ",
  },
  {
    countryCode: "TKL",
    countryNameTH: "โตเกเลา",
    countryNameEN: "Tokelau",
    ISO: "TK",
  },
  {
    countryCode: "TKM",
    countryNameTH: "เติร์กเมนิสถาน",
    countryNameEN: "Turkmenistan",
    ISO: "TM",
  },
  {
    countryCode: "TLS",
    countryNameTH: "ติมอร์ตะวันออก",
    countryNameEN: "East Timor",
    ISO: "TL",
  },
  {
    countryCode: "TON",
    countryNameTH: "ตองกา",
    countryNameEN: "Tonga",
    ISO: "TO",
  },
  {
    countryCode: "TTO",
    countryNameTH: "ตรินิแดดและโตเบโก",
    countryNameEN: "Trinidad and Tobago",
    ISO: "TT",
  },
  {
    countryCode: "TUN",
    countryNameTH: "ตูนิเซีย",
    countryNameEN: "Tunisia",
    ISO: "TN",
  },
  {
    countryCode: "TUR",
    countryNameTH: "ตุรกี",
    countryNameEN: "Turkey",
    ISO: "TR",
  },
  {
    countryCode: "TUV",
    countryNameTH: "ตูวาลู",
    countryNameEN: "Tuvalu",
    ISO: "TV",
  },
  {
    countryCode: "TWN",
    countryNameTH: "ไต้หวัน",
    countryNameEN: "Taiwan",
    ISO: "TW",
  },
  {
    countryCode: "TZA",
    countryNameTH: "แทนซาเนีย",
    countryNameEN: "Tanzania",
    ISO: "TZ",
  },
  {
    countryCode: "UGA",
    countryNameTH: "ยูกันดา",
    countryNameEN: "Uganda",
    ISO: "UG",
  },
  {
    countryCode: "UKR",
    countryNameTH: "ยูเครน",
    countryNameEN: "Ukraine",
    ISO: "UA",
  },
  {
    countryCode: "UMI",
    countryNameTH: "เกาะนอกรีตของสหรัฐฯ",
    countryNameEN: "U.S. Minor Outlying Islands",
    ISO: "UM",
  },
  {
    countryCode: "URY",
    countryNameTH: "อุรุกวัย",
    countryNameEN: "Uruguay",
    ISO: "UY",
  },
  {
    countryCode: "USA",
    countryNameTH: "สหรัฐอเมริกา",
    countryNameEN: "United States",
    ISO: "US",
  },
  {
    countryCode: "UZB",
    countryNameTH: "อุซเบกิสถาน",
    countryNameEN: "Uzbekistan",
    ISO: "UZ",
  },
  {
    countryCode: "VAT",
    countryNameTH: "เมืองวาติกัน",
    countryNameEN: "Vatican City",
    ISO: "VA",
  },
  {
    countryCode: "VCT",
    countryNameTH: "เซนต์วินเซนต์และเกรนาดีนส์",
    countryNameEN: "Saint Vincent and the Grenadines",
    ISO: "VC",
  },
  {
    countryCode: "VEN",
    countryNameTH: "เวเนซุเอลา",
    countryNameEN: "Venezuela",
    ISO: "VE",
  },
  {
    countryCode: "VGB",
    countryNameTH: "หมู่เกาะบริติชเวอร์จิน",
    countryNameEN: "British Virgin Islands",
    ISO: "VG",
  },
  {
    countryCode: "VIR",
    countryNameTH: "หมู่เกาะเวอร์จินของสหรัฐอเมริกา",
    countryNameEN: "U.S. Virgin Islands",
    ISO: "VI",
  },
  {
    countryCode: "VNM",
    countryNameTH: "เวียดนาม",
    countryNameEN: "Vietnam",
    ISO: "VN",
  },
  {
    countryCode: "VUT",
    countryNameTH: "วานูอาตู",
    countryNameEN: "Vanuatu",
    ISO: "VU",
  },
  {
    countryCode: "WLF",
    countryNameTH: "วาลลิสและฟุตูนา",
    countryNameEN: "Wallis and Futuna",
    ISO: "WF",
  },
  {
    countryCode: "WSM",
    countryNameTH: "ซามัว",
    countryNameEN: "Samoa",
    ISO: "WS",
  },
  {
    countryCode: "XKX",
    countryNameTH: "โคโซโว",
    countryNameEN: "Kosovo",
    ISO: "XK",
  },
  {
    countryCode: "YEM",
    countryNameTH: "เยเมน",
    countryNameEN: "Yemen",
    ISO: "YE",
  },
  {
    countryCode: "ZAF",
    countryNameTH: "แอฟริกาใต้",
    countryNameEN: "South Africa",
    ISO: "ZA",
  },
  {
    countryCode: "ZMB",
    countryNameTH: "แซมเบีย",
    countryNameEN: "Zambia",
    ISO: "ZM",
  },
  {
    countryCode: "ZWE",
    countryNameTH: "ประเทศซิมบับเว",
    countryNameEN: "Zimbabwe",
    ISO: "ZW",
  },
]);
